### ISSUE TITLE
v^1.xx.xx doesn't support ssr in react by referencing window

### ISSUE THREAD

**Issue by victorthevong** [kaimallea/isMobile#104]
v0.5.1  does call window reference and handles it if it doesn't exist.

in v^1.xx.xx it calls window which doesn't allow  ssr.

For those wondering any ANT DESIGN users who use the latest version (^3.23.1) ismobilejs is used by some packages and has updated to ismobilejs v1.xx.xx.

In your package.json in resolutions place ismobilejs as 0.5.1 for ssr

**Comment by zkid1412z** [comment]
We use Next.js framework with Ant Design and had the same problem with this due to natively SSR feature of the Next.js. The workaround is to use Dependency Resolutions to fix the version back to 0.5.1. https://www.npmjs.com/package/npm-force-resolutions

**Comment by kaimallea** [comment]
I'm sorry about this; fix for the dist version incoming that stops referencing `window` explicitly and instead references global `this`
