### ISSUE TITLE
Add Support for iPad on iOS 13

### ISSUE THREAD

**Issue by gk1041** [kaimallea/isMobile#109]
For iPad on iOS 13 the term `iPad` no longer appears in the `user-agent`. The user agent for iPad on iOS 13 is this:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)
```

The solution to check for iPad on iOS is:

```js
let isIOS = /iPad|iPhone|iPod/.test(navigator.platform) ||
(navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
```

Reference to solution here: https://stackoverflow.com/a/58064481/3787150

**Comment by kaimallea** [comment]
Thanks for reporting this, will take a look!

**Comment by WookashWackomy** [comment]
Hey @kaimallea. Any updates on that matter?

**Comment by kaimallea** [comment]
Added in #109
