### ISSUE TITLE
v1 no longer supports older browsers

### ISSUE THREAD

**Issue by mattcolman** [kaimallea/isMobile#115]
Hi, v1 builds to cjs and still includes the `const` keyword. This means anyone installing this library via npm and running it in the browser cannot support <=ie10 and <=safari 9. I haven't used parcel before but I imagine you just need to tweak the settings to babelify `const` to `var`.

This worked in v0.

**Comment by motla** [comment]
same issue here!

**Comment by eXponenta** [comment]
There is babel for this case. You can transpile it themselfs in your build process.

**Comment by BernsteinA** [comment]
Shouldn't have to use babel to transpile a dependency of a dependency of a dependency of a project I'm working on.
I **think** that this is the problem line: https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/config/tsconfig.json#L12
(yes, it's even further down the dependency chain from the code I'm actually writing)

**Comment by notorigine** [comment]
It is also causing issues in other repos using isMobile as a dependancy - see [Pixijs #6511](https://github.com/pixijs/pixi.js/issues/6511).

Any ETA on a fix @kaimallea please? 😇

**Comment by kaimallea** [comment]
My apologies for the delay! PRs are welcome! Fix via #120
