### ISSUE TITLE
Facebook mobile (ipad) app detected incorrectly as phone

### ISSUE THREAD

**Issue by dlt-** [kaimallea/isMobile#22]
Facebook Ipad app has an integrated browser, which user agent contains a lot of things:

Mozilla/5.0 (iPad; CPU OS 8_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B410 [FBAN/FBIOS;FBAV/20.1.0.15.10;FBBV/5758778;FBDV/iPad5,4;FBMD/iPad;FBSN/iPhone OS;FBSV/8.1;FBSS/2; FBCR/;FBID/tablet;FBLC/fi_FI;FBOP/1]

Regexp for Phone detection catches "iPhone OS" -> incorrect detection

The easiest fix is propably to remove anything after [FBAN, like this:

      var ua = userAgent || navigator.userAgent;
      var tmp	= ua.split("[FBAN");
      if (typeof tmp[1] != "undefined") { ua = tmp[0];  }

**Comment by arthurmuchir** [comment]
+ 1

**Comment by percyhanna** [comment]
Likely a simpler solution would be to use logic similar to how [Android Tablet is detected](https://github.com/kaimallea/isMobile/blob/master/isMobile.js#L65). If it's iPad, then it can't be an iPhone as well.

**Comment by kaimallea** [comment]
Better late than never. :smiley:  PRs welcome, btw.
