### ISSUE TITLE
(Requirejs) Using r.js to combine AMD files include isMobile.js throw error: Mismatched anonymous define() module: [object Object]

### ISSUE THREAD

**Issue by mc-zone** [kaimallea/isMobile#23]
I'm not sure this is an issue or just my wrong.
At first, I include `isMobile.js` in my AMD project use the following code, it worked very well.
```javascript
require( [ "app", "isMobile" ], function(App, isMobile) {
    //...
});

```
But when I use `r.js` to optimize and combine my project and run again, the following error has occurred.
```
Mismatched anonymous define() module: [object Object]
```
Then I found  the description of this error [form the page of requirejs](http://requirejs.org/docs/errors.html#mismatch) .
So I think the problem may be in the line #105~106 of `isMobile.js`:
```javascript
 //AMD
define(global.isMobile = instantiate());
```
I tried to modify the code to look like this:
```javascript
//AMD
define( 'isMobile', [], global.isMobile = instantiate() );
```
Then it worked fine.

So I just submit this issue, and I'm not a veteran of the requirejs, anyone could give me some advice on this?

Btw, very nice project :).

**Comment by kaimallea** [comment]
You are probably doing it the correct way. Feel free to submit a pull request, or I can patch it up if you don't want to. :smiley:

**Comment by pilaas** [comment]
Please, update Bower with this version

**Comment by kaimallea** [comment]
@pilaas I've pushed a new tag, which should be reflected in bower. Thanks for the heads up!
