### ISSUE TITLE
Galaxy Tab showing as phone in Chrome Inspector

### ISSUE THREAD

**Issue by zach-adams** [kaimallea/isMobile#30]
In Chrome Inspector the Galaxy Tab shows as phone, don't have a real Galaxy Tab so I can't confirm whether it's just the inspector.

http://i.imgur.com/4MDm1Qd.png

**Comment by kaimallea** [comment]
Galaxy Tab is no longer an option in Chrome. I'll add some tests against Galaxy Tab's user agent, and if it passes, I'll close it for now.

**Comment by kaimallea** [comment]
Closing as the Galaxy Tab is still no longer an option in Chrome since July 2015.
