### ISSUE TITLE
Questions about the effects of User-Agent Reduction

### ISSUE THREAD

**Issue by RP-KentaroAoki** [kaimallea/isMobile#308]
@kaimallea 
Chrome has announced its plans for User-Agent string reduction, will this affect "isMobile"? If so, will there be a fix?

Thank you for your confirmation.

[User-Agent Reduction Origin Trial and Dates](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html)

**Comment by 0x54321** [comment]
The deprecation trial will be starting soon:
https://developer.chrome.com/docs/privacy-sandbox/user-agent/

**Comment by Aymkdn** [comment]
This lib is based on [UserAgent](https://github.com/kaimallea/isMobile/blob/master/src/isMobile.ts), so indeed, it will be impacted.

**Comment by kaimallea** [comment]
I will work on this soon; closing bc this is a dupe of #118, which I will use to track this
