### ISSUE TITLE
Suggestion - Screen Resolution

### ISSUE THREAD

**Issue by velkymx** [kaimallea/isMobile#31]
You should add resolution detection for redirect. My android tablet is showing up as mobile but it is a HD screen. Anything with a resolution above 1280 x 800 should show as a tablet.

**Comment by velkymx** [comment]
var width = screen.width;
var height = screen.height;

**Comment by kaimallea** [comment]
Shouldn't resolution-specific things be left to media queries? I'm not sure resolution checks should fall under mobile device detection; UA sniffing is already unreliable, but at least it matches a specific device string. Resolution checks would be even more unreliable. What do you think?

**Comment by kaimallea** [comment]
Closing for now.
