### ISSUE TITLE
Amazon devices

### ISSUE THREAD

**Issue by asymmetric** [kaimallea/isMobile#32]
Hi,

Would you be interested in a PR that adds explicit support for Amazon devices?

I would use [this](https://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html) page as a reference.

**Comment by kaimallea** [comment]
Aren't they all considered Android devices? Perhaps getting them to validate under the Android check is helpful; I'm not sure if the Amazon device specificity is necessary? What do you think?

**Comment by asymmetric** [comment]
Sure, but they use a different app store. So if you only want to display Amazon apps links on Amazon devices, you need to be able to reliably detect them.

**Comment by kaimallea** [comment]
Makes sense.
