### ISSUE TITLE
Not detect windows phone

### ISSUE THREAD

**Issue by crashbell** [kaimallea/isMobile#36]
I'm testing with Windows Phone Lumia and this isn't working. It keeps showing apple phone.

**Comment by crashbell** [comment]
I found out that the user agent of Windows Phone includes `iPhone` and `Android` texts. Please close this issue. Thanks!

**Comment by kaimallea** [comment]
Can you share the exact user agent string from the Windows Phone?

**Comment by crashbell** [comment]
F.Y.I

`Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 730 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537`

That user agent string is confusing by the way.

**Comment by kaimallea** [comment]
Wow that's one crazy UA string. Thx for sharing it for reference!
