### ISSUE TITLE
Nokia Lumia 930 is detected as apple device

### ISSUE THREAD

**Issue by stenit** [kaimallea/isMobile#37]
The Nokia Lumia 930 device is recognized as apple device when checking "isMobile.apple.device"

**Comment by kaimallea** [comment]
@stenit Hi, thanks for reporting this. Any way you can provide the user agent for your Lumia device?

**Comment by kaimallea** [comment]
Hmm a quick Google search reveals that the device pretends to be both Android and iPhone by including those strings in its user agent: http://wmpoweruser.com/wp8-1-update-1s-ie-user-agent-pretends-to-be-android-4-0-and-ios-7-good-enough-to-fool-gmail/

**Comment by crashbell** [comment]
It might relevant to #36

**Comment by kaimallea** [comment]
Closing as the phone's user agent tries to be everything. The downside of UA sniffing.
