### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JaredSartin** [kaimallea/isMobile#38]
Hey! I am assuming this is under the MIT license, but for sake use in projects you should include and official license file!

**Comment by shinnn** [comment]
> this is under the MIT license

No, isMobile is a [Public Domain](http://creativecommons.org/publicdomain/zero/1.0/) software. https://github.com/kaimallea/isMobile/blob/84c93a48e09506267241f9f33fd3ae97743f52db/isMobile.js#L10

**Comment by kaimallea** [comment]
Hi @JaredSartin, @shinn is correct -- this software is dedicated to the Public Domain, so there is no license to deal with. I can, however, make it more obvious by putting it in the README file.

**Comment by JaredSartin** [comment]
Awesome - thanks guys. I was rounding up licenses for a project I am working on, was able to find all the others in the license file or readme, but this one through me off. Should have known to look in the source too!
