### ISSUE TITLE
Restructuring the module

### ISSUE THREAD

**Issue by softwarespot** [kaimallea/isMobile#40]
How about opting for the universal style of defining a module e.g.

```javascript
(function isMobileModule(root, factory) {
    // Define the UMD structure
})(window, (function isMobileInterface() {
    // Define the module itself
}));
```

If you would like me to send a PR let me know.

**Comment by kaimallea** [comment]
Sure, please send a PR. Thanks for the other fix as well.

**Comment by softwarespot** [comment]
No worries. I will do it this evening.

**Comment by kaimallea** [comment]
See comment on PR.
