### ISSUE TITLE
Installation via Bower

### ISSUE THREAD

**Issue by JulianLaval** [kaimallea/isMobile#50]
Brilliant utility!

Any chance on it being available via Bower? :smile:

**Comment by elvismdev** [comment]
It is already, do:
`bower install --save isMobile`

**Comment by JulianLaval** [comment]
Woops, should've notice the `bower.json`!

Maybe worth amending the README installation options / add a badge to reflect this?

**Comment by kaimallea** [comment]
Done! Took me long enough. 😄
