### ISSUE TITLE
problem with webpack

### ISSUE THREAD

**Issue by YannickBochatay** [kaimallea/isMobile#53]
The npm package doesn't have the same name as the AMD module (ismobilejs versus isMobile).
So when you use webpack, you have to create an alias. 
I think it should be fine if you don't give a name to your AMD module (l132) :

``` javascript
define([], global.isMobile = instantiate());
```

instead of 

``` javascript
define('isMobile', [], global.isMobile = instantiate());
```

**Comment by kaimallea** [comment]
Hey @YannickBochatay, thanks for reporting this! Pull request? 😃
