### ISSUE TITLE
Detect when change resolution

### ISSUE THREAD

**Issue by vitorluis** [kaimallea/isMobile#60]
Today, I'm using the current production version. When I'm testing on Chrome and changing phone to tablet, or phone to desktop, the plugin do not detect this changes.

This is just an improvement, but can be useful.

**Comment by kaimallea** [comment]
Hi, this library executes during the initial page load, so the results cannot change by using Chrome dev tools to emulate a mobile device. You will need to reload the page again after using the Chrome dev tools to use a mobile view/
