### ISSUE TITLE
Upgrade/update to ES6

### ISSUE THREAD

**Issue by chrisbenseler** [kaimallea/isMobile#61]
Hi @kaimallea I'm using this lib, it's awesome.

Is there any plan to rewrite it using ES6 features, and then browserify to generate an dist file?

[]s

**Comment by kaimallea** [comment]
Yes, I want to do this. No ETA, though.

**Comment by kaimallea** [comment]
#77 modernized the tests, dependencies and build step. However, using ES6 in the source file and then bundling with browserify or webpack will introduce overhead that doubles the size of the generated file for browsers. :disappointed:
