### ISSUE TITLE
'ismobilejs' import is an empty object

### ISSUE THREAD

**Issue by b12k** [kaimallea/isMobile#94]
Hello,
After upgrading `ismobilejs` version from `v0.5.2`, which is present on NPM but not in github releases btw, to `v1.0.1` the result of webpacks import function is `{}`.
Executed in `mounted` hook of js framework, used in browser, built with webpack.

```javascript
  const { default: isMobile } = await import('ismobilejs');
  console.log(isMobile); //> {}
```

Thank you in advance!

**Comment by sectsect** [comment]
I have same problem.
```js
import isMobile from 'ismobilejs';

export default () => {
  console.log(isMobile);
  // {}
};
```

**Comment by kaimallea** [comment]
Yikes, sorry about the breakage! Fix incoming
