### ISSUE TITLE
Error on v1.0.2

### ISSUE THREAD

**Issue by sectsect** [kaimallea/isMobile#96]
`isMobile.xxxxx` on v1.0.2  returns `undefined`.

- `isMobile.any`
- `isMobile.phone`
- `isMobile.tablet`

And `isMobile.xxxxx.xxxxx` returns following error.
```
Uncaught TypeError: Cannot read property 'phone' of undefined
```

- `isMobile.apple.phone`
- `isMobile.apple.ipod`
- `isMobile.apple.tablet`
- `isMobile.apple.device` (any mobile Apple device)
- `isMobile.android.phone`
- `isMobile.android.tablet`
- `isMobile.android.device` (any mobile Android device; OkHttp user agents will match this)
- `isMobile.amazon.phone`
- `isMobile.amazon.tablet`
- `isMobile.amazon.device` (any mobile Amazon Silk device)
- `isMobile.windows.phone`
- `isMobile.windows.tablet`
- `isMobile.windows.device` (any mobile Windows device)
- `isMobile.other.blackberry_10`
- `isMobile.other.blackberry`
- `isMobile.other.opera` (Opera Mini)
- `isMobile.other.firefox`
- `isMobile.other.chrome`
- `isMobile.other.device` (any "Other" device)

Related #94

**Comment by kaimallea** [comment]
thx for reporting, will take a look. interesting that tests pass, but sounds like I need to add more exhaustive tests.

**Comment by kaimallea** [comment]
@sectsect hey, in which environment are you using the library? I setup a runkit notebook to test v1.0.2 and it is outputting the values -- https://runkit.com/kmallea/test-ismobile-v1-0-2

**Comment by sectsect** [comment]
@kaimallea 

I'm using it on browser.
It works fine on `v0.5.2`.
```js
import isMobile from 'ismobilejs';

export default () => {
  console.log(isMobile.any); // undefined
  console.log(isMobile.phone); // undefined
  console.log(isMobile.tablet); // undefined
};
```

**Comment by kaimallea** [comment]
@sectsect hmm, I think the breaking change is that `isMobile` is not automatically executed for you. What happens when you call `isMobile()` after importing -- are you receiving the object then?

**Comment by sectsect** [comment]
@kaimallea 

`isMobile()` returns correct object.

```js
import isMobile from 'ismobilejs';

export default () => {
  console.log(isMobile());
};
```

### Return
```json
{
    "apple": {
        "phone": true,
        "ipod": false,
        "tablet": false,
        "device": true
    },
    "amazon": {
        "phone": false,
        "tablet": false,
        "device": false
    },
    "android": {
        "phone": false,
        "tablet": false,
        "device": false
    },
    "windows": {
        "phone": false,
        "tablet": false,
        "device": false
    },
    "other": {
        "blackberry": false,
        "blackberry10": false,
        "opera": false,
        "firefox": false,
        "chrome": false,
        "device": false
    },
    "any": true,
    "phone": true,
    "tablet": false
}
```

**Comment by kaimallea** [comment]
Great, I'll close this and assign an issue to myself to update the README to document this, and other use cases, so usage is clearer. In this case, when used as a module you are given the opportunity to pass in your own useragent string and so you must execute it yourself.
